### PR TITLE
Add multivalue handling and ability to get attributes from multiple connectors

### LINKED ISSUE #19: Concatenate multiple single-value attributes to a multi-value attribut
Hi,
In a import flow rule, is there a way to merge values from multiple attributes, into a single multi-value attribute?
I tried something like the following, but source attributes are concatenated into a single string.
```
<FlowRule Name="MyFlowRule" Direction="Import" xsi:type="FlowRule">
  <SourceExpression>
    <Source xsi:type="Attribute" Name="mailAddr1" />
    <Source xsi:type="Attribute" Name="mailAddr2" />
    <Source xsi:type="Attribute" Name="mailAddr3" />
  </SourceExpression>
  <Target Name="mailAddresses" ActionOnNullSource="None" />
</FlowRule>
```

Or should I specify somewhere that `mailAddresses` is a multi-valued attribute?

### PR DESCRIPTION
**Pull request by ruliane**
fix #19

### CODE REVIEW

**Comment by ruliane** [comment]
Here are a couple of examples.

### 1. Append mail addresses from multiple connectors to a single MV attribute:
```
<FlowRule xsi:type="FlowRule" Name="mailAddresses" Direction="Import">
  <SourceExpression>
    <Source xsi:type="Attribute" Name="mail" />
    <Source xsi:type="MultiValueAttribute" Name="proxyAddresses" />
    <Source xsi:type="Attribute" Name="mail" FromOtherConnector="AD example.org" />
    <Source xsi:type="MultiValueAttribute" Name="proxyAddresses" FromOtherConnector="AD example.org" />
  </SourceExpression>
  <Target Name="mailAddresses" ActionOnNullSource="Delete" />
</FlowRule>
```


### 2. List connected Management Agents:
Constant values will be present only if a connected object is found in the connector space.
```
<FlowRule xsi:type="FlowRule" Name="ConnectedMAs" Direction="Import">
  <SourceExpression>
    <Source xsi:type="Constant" Value="LDAP-Directory" />
    <Source xsi:type="Constant" Value="AD" FromOtherConnector="AD Example.org" />
    <Source xsi:type="Constant" Value="Phone" FromOtherConnector="Phoning system" />
  </SourceExpression>
  <Target Name="ConnectedSources" ActionOnNullSource="Delete" />
</FlowRule>
```

**Comment by ruliane** [comment]
FYI, I completely rewrote my commit to better handle special situation.
This is available on my fork, since @sorengranfeldt doesn't seem to pull changes anymore.

**Comment by sorengranfeldt** [comment]
I'll be glad to accept pull request. You need to test the other Transforms to make sure that there are no breaking changes in these since you seem to have implemented change in the core. Also, please provide documentation and samples for requests for the Wiki documentation. See Wiki for documentation samples, like - https://github.com/sorengranfeldt/mare/wiki/Transform-MultiValueReplace

**Comment by ruliane** [comment]
For this improvement to work, I deeply reworked the logic: source values are no more converted to strings. They are processed as a List of sources. The logic is the following.

For each Source:
- Get Source (object and attribute value)
- Apply Transforms on Source value
- Append (transformed) value to list

Finally:
- Apply Transforms on Target
- **If Target if monovalued**, concatenate values to get a String
- Commit target value (to MV or CS, depending on flow direction)



It doesn't change anything when applying Source Transforms, but it might break some Transforms when they are applied on Target (since Target is now a List, not a String). I will test as much as possible, but you will need to test as well, since I can't cover every use case.


Examples are supplied in previous comments. (https://github.com/sorengranfeldt/mare/pull/20#issuecomment-877223084)

**Comment by sorengranfeldt** [comment]
This seems like a very comprehensive rewrite with too many potential breaking changes. It make sense that you maintain your own fork with this. I will reject the pull request for now.

**Comment by ruliane** [comment]
@sorengranfeldt: I also implemented deprovisioning in my fork. So far, works well in production for a customer.

**Pull request closed without merging**
