### PR TITLE
Support for deprovisioning in external dll and config.

### PR DESCRIPTION
**Pull request by EminaKaric**
Initialize of external dll called at load assembly

### CODE REVIEW

**Comment by sorengranfeldt** [comment]
Thank you. Have you written documentation and any samples that can be included for this..?

**Comment by EminaKaric** [comment]
There is documentation and examples in the wiki. The wiki contains only the added/updated documentation pages. 

https://github.com/EminaKaric/mare/wiki

I see now some minor issues in the documentation but the examples should be ok. I'll update the wiki before lunch.

**Comment by EminaKaric** [comment]
The wiki should look a bit better now. I've also added a section for how to configure it in the connector.

**Comment by sorengranfeldt** [comment]
I’ll look into to this as soon as time allows

**Comment by EminaKaric** [comment]
I'm happy to make any changes to the code or documentation if it simplifies anything on your side.

**Pull request merged**
